# Generated by Django 5.2.17 on 2026-10-06 07:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='назва')),
                ('default_unit', models.CharField(choices=[('g', 'г'), ('ml', 'мл'), ('pcs', 'шт')], default='g', max_length=3, verbose_name='одиниця')),
                ('calories_per_100', models.FloatField(verbose_name='ккал на 100 г')),
                ('protein_per_100', models.FloatField(blank=True, null=True, verbose_name='білки на 100 г')),
                ('fat_per_100', models.FloatField(blank=True, null=True, verbose_name='жири на 100 г')),
                ('carbs_per_100', models.FloatField(blank=True, null=True, verbose_name='вуглеводи на 100 г')),
                ('grams_per_piece', models.FloatField(blank=True, null=True, verbose_name='вага 1 шт, г')),
                ('usda_fdc_id', models.IntegerField(blank=True, null=True, verbose_name='USDA FDC ID')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='кількість')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='придатний до')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_items', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fridge.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'продукт у холодильнику',
                'verbose_name_plural': 'продукти в холодильнику',
                'ordering': ['product__name'],
            },
        ),
    ]
