# Generated by Django 5.2.17 on 2026-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usda_query',
            field=models.CharField(blank=True, max_length=255, verbose_name='запит до USDA'),
        ),
    ]
