PRODUCTS = {
    "Куряче філе": {"query": "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw", "unit": "g"},
    "Куряче стегно": {"query": "Chicken, broilers or fryers, thigh, meat only, raw", "unit": "g"},
    "Курячі гомілки": {"query": "Chicken, broilers or fryers, drumstick, meat and skin, raw", "unit": "g"},
    "Курячі крильця": {"query": "Chicken, broilers or fryers, wing, meat and skin, raw", "unit": "g"},
    "Куряча печінка": {"query": "Chicken, liver, all classes, raw", "unit": "g"},
    "Фарш курячий": {"query": "Chicken, ground, raw", "unit": "g"},
    "Індиче філе": {"query": "Turkey, whole, breast, meat only, raw", "unit": "g"},
    "Яловичина": {"query": "Beef, chuck, arm pot roast, separable lean and fat, trimmed to 0\" fat, all grades, raw", "unit": "g"},
    "Фарш яловичий": {"query": "Beef, ground, 90% lean meat / 10% fat, raw", "unit": "g"},
    "Яловича печінка": {"query": "Beef, variety meats and by-products, liver, raw", "unit": "g"},
    "Телятина": {"query": "Veal, leg (top round), separable lean only, raw", "unit": "g"},
    "Свинина": {"query": "Pork, fresh, loin, whole, separable lean and fat, raw", "unit": "g"},
    "Фарш свинячий": {"query": "Pork, fresh, ground, raw", "unit": "g"},
    "Свинячі ребра": {"query": "Pork, fresh, spareribs, separable lean and fat, raw", "unit": "g"},
    "Фарш змішаний": {"query": "Beef, ground, 80% lean meat / 20% fat, raw", "unit": "g"},
    "Баранина": {"query": "Lamb, domestic, leg, whole (shank and sirloin), separable lean and fat, trimmed to 1/4\" fat, choice, raw", "unit": "g"},
    "Сало": {"query": "Pork, fresh, backfat, raw", "unit": "g"},
    "Бекон": {"query": "Pork, cured, bacon, unprepared", "unit": "g"},
    "Шинка": {"query": "Ham, sliced, regular (approximately 11% fat)", "unit": "g"},
    "Ковбаса варена": {"query": "Bologna, beef and pork", "unit": "g"},
    "Ковбаса копчена": {"query": "Sausage, Polish, pork and beef, smoked", "unit": "g"},
    "Сосиски": {"query": "Frankfurter, beef and pork", "unit": "g"},

    "Лосось": {"query": "Fish, salmon, Atlantic, farmed, raw", "unit": "g"},
    "Минтай": {"query": "Fish, pollock, Alaska, raw", "unit": "g"},
    "Хек": {"query": "Fish, whiting, mixed species, raw", "unit": "g"},
    "Тріска": {"query": "Fish, cod, Atlantic, raw", "unit": "g"},
    "Скумбрія": {"query": "Fish, mackerel, Atlantic, raw", "unit": "g"},
    "Оселедець": {"query": "Fish, herring, Atlantic, raw", "unit": "g"},
    "Тунець консервований": {"query": "Fish, tuna, light, canned in water, drained solids", "unit": "g"},
    "Сардини консервовані": {"query": "Fish, sardine, Atlantic, canned in oil, drained solids with bone", "unit": "g"},
    "Креветки": {"query": "Crustaceans, shrimp, raw", "unit": "g"},
    "Кальмари": {"query": "Mollusks, squid, mixed species, raw", "unit": "g"},
    "Крабові палички": {"query": "Crustaceans, crab, alaska king, imitation, made from surimi", "unit": "g"},

    "Яйце куряче": {"query": "Egg, whole, raw, fresh", "unit": "pcs", "grams_per_piece": 50},
    "Яйце перепелине": {"query": "Egg, quail, whole, fresh, raw", "unit": "pcs", "grams_per_piece": 10},

    "Молоко 2.5%": {"query": "Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D", "unit": "ml"},
    "Молоко 3.2%": {"query": "Milk, whole, 3.25% milkfat, with added vitamin D", "unit": "ml"},
    "Кефір": {"query": "Kefir, lowfat, plain", "unit": "ml"},
    "Вершки 10%": {"query": "Cream, fluid, half and half", "unit": "ml"},
    "Вершки 33%": {"query": "Cream, fluid, heavy whipping", "unit": "ml"},
    "Сметана": {"query": "Cream, sour, cultured", "unit": "g"},
    "Йогурт натуральний": {"query": "Yogurt, plain, whole milk", "unit": "g"},
    "Грецький йогурт": {"query": "Yogurt, Greek, plain, whole milk", "unit": "g"},
    "Сир кисломолочний": {"query": "Cheese, cottage, lowfat, 2% milkfat", "unit": "g"},
    "Сир твердий": {"query": "Cheese, cheddar", "unit": "g"},
    "Моцарела": {"query": "Cheese, mozzarella, whole milk", "unit": "g"},
    "Пармезан": {"query": "Cheese, parmesan, grated", "unit": "g"},
    "Фета": {"query": "Cheese, feta", "unit": "g"},
    "Рікота": {"query": "Cheese, ricotta, whole milk", "unit": "g"},
    "Вершковий сир": {"query": "Cheese, cream", "unit": "g"},
    "Вершкове масло": {"query": "Butter, salted", "unit": "g"},
    "Згущене молоко": {"query": "Milk, canned, condensed, sweetened", "unit": "g"},

    "Рис": {"query": "Rice, white, long-grain, regular, raw, unenriched", "unit": "g"},
    "Рис бурий": {"query": "Rice, brown, long-grain, raw", "unit": "g"},
    "Гречка": {"query": "Buckwheat groats, roasted, dry", "unit": "g"},
    "Вівсянка": {"query": "Cereals, oats, regular and quick, not fortified, dry", "unit": "g"},
    "Пшоно": {"query": "Millet, raw", "unit": "g"},
    "Булгур": {"query": "Bulgur, dry", "unit": "g"},
    "Кус-кус": {"query": "Couscous, dry", "unit": "g"},
    "Кіноа": {"query": "Quinoa, uncooked", "unit": "g"},
    "Перлова крупа": {"query": "Barley, pearled, raw", "unit": "g"},
    "Манна крупа": {"query": "Semolina, enriched", "unit": "g"},
    "Кукурудзяна крупа": {"query": "Cornmeal, degermed, enriched, yellow", "unit": "g"},
    "Макарони": {"query": "Pasta, dry, unenriched", "unit": "g"},
    "Локшина яєчна": {"query": "Noodles, egg, dry, unenriched", "unit": "g"},
    "Рисова локшина": {"query": "Rice noodles, dry", "unit": "g"},
    "Борошно": {"query": "Wheat flour, white, all-purpose, enriched, bleached", "unit": "g"},
    "Борошно цільнозернове": {"query": "Wheat flour, whole-grain", "unit": "g"},
    "Борошно житнє": {"query": "Rye flour, dark", "unit": "g"},
    "Крохмаль кукурудзяний": {"query": "Cornstarch", "unit": "g"},
    "Панірувальні сухарі": {"query": "Bread, crumbs, dry, grated, plain", "unit": "g"},

    "Хліб пшеничний": {"query": "Bread, white, commercially prepared (includes soft bread crumbs)", "unit": "g", "fdc_id": 174924},
    "Хліб житній": {"query": "Bread, rye", "unit": "g"},
    "Лаваш": {"query": "Bread, pita, white, enriched", "unit": "g"},
    "Тортилья пшенична": {"query": "Tortillas, ready-to-bake or -fry, flour, shelf stable", "unit": "g"},
    "Листкове тісто": {"query": "Puff pastry, frozen, ready-to-bake", "unit": "g"},

    "Квасоля суха": {"query": "Beans, kidney, all types, mature seeds, raw", "unit": "g"},
    "Квасоля консервована": {"query": "Beans, kidney, all types, mature seeds, canned", "unit": "g"},
    "Квасоля стручкова": {"query": "Beans, snap, green, raw", "unit": "g"},
    "Сочевиця суха": {"query": "Lentils, raw", "unit": "g"},
    "Горох сухий": {"query": "Peas, split, mature seeds, raw", "unit": "g"},
    "Нут": {"query": "Chickpeas (garbanzo beans, bengal gram), mature seeds, raw", "unit": "g"},
    "Горошок зелений": {"query": "Peas, green, raw", "unit": "g"},
    "Кукурудза консервована": {"query": "Corn, sweet, yellow, canned, whole kernel, drained solids", "unit": "g"},

    "Картопля": {"query": "Potatoes, flesh and skin, raw", "unit": "g"},
    "Батат": {"query": "Sweet potato, raw, unprepared", "unit": "g"},
    "Морква": {"query": "Carrots, raw", "unit": "g"},
    "Цибуля": {"query": "Onions, raw", "unit": "g"},
    "Цибуля зелена": {"query": "Onions, spring or scallions (includes tops and bulb), raw", "unit": "g"},
    "Часник": {"query": "Garlic, raw", "unit": "g"},
    "Капуста": {"query": "Cabbage, raw", "unit": "g"},
    "Капуста пекінська": {"query": "Cabbage, chinese (pe-tsai), raw", "unit": "g"},
    "Капуста червона": {"query": "Cabbage, red, raw", "unit": "g"},
    "Броколі": {"query": "Broccoli, raw", "unit": "g"},
    "Цвітна капуста": {"query": "Cauliflower, raw", "unit": "g"},
    "Помідор": {"query": "Tomatoes, red, ripe, raw, year round average", "unit": "g"},
    "Огірок": {"query": "Cucumber, with peel, raw", "unit": "g"},
    "Перець солодкий": {"query": "Peppers, sweet, red, raw", "unit": "g"},
    "Перець чилі": {"query": "Peppers, hot chili, red, raw", "unit": "g"},
    "Буряк": {"query": "Beets, raw", "unit": "g"},
    "Гарбуз": {"query": "Pumpkin, raw", "unit": "g"},
    "Кабачок": {"query": "Squash, summer, zucchini, includes skin, raw", "unit": "g"},
    "Баклажан": {"query": "Eggplant, raw", "unit": "g"},
    "Шпинат": {"query": "Spinach, raw", "unit": "g"},
    "Салат листовий": {"query": "Lettuce, green leaf, raw", "unit": "g"},
    "Селера": {"query": "Celery, raw", "unit": "g"},
    "Редиска": {"query": "Radishes, raw", "unit": "g"},
    "Печериці": {"query": "Mushrooms, white, raw", "unit": "g"},
    "Гливи": {"query": "Mushrooms, oyster, raw", "unit": "g"},
    "Імбир": {"query": "Ginger root, raw", "unit": "g"},
    "Авокадо": {"query": "Avocados, raw, all commercial varieties", "unit": "g"},
    "Квашена капуста": {"query": "Sauerkraut, canned, solids and liquids", "unit": "g"},
    "Огірки мариновані": {"query": "Pickles, cucumber, dill or kosher dill", "unit": "g"},
    "Оливки": {"query": "Olives, ripe, canned (small-extra large)", "unit": "g"},
    "Томатна паста": {"query": "Tomato products, canned, paste, without salt added", "unit": "g"},
    "Томати консервовані": {"query": "Tomatoes, red, ripe, canned, packed in tomato juice", "unit": "g"},
    "Томатний соус": {"query": "Tomato products, canned, sauce", "unit": "g"},

    "Яблуко": {"query": "Apples, raw, with skin", "unit": "pcs", "grams_per_piece": 180},
    "Груша": {"query": "Pears, raw", "unit": "pcs", "grams_per_piece": 170},
    "Банан": {"query": "Bananas, raw", "unit": "pcs", "grams_per_piece": 120},
    "Апельсин": {"query": "Oranges, raw, all commercial varieties", "unit": "pcs", "grams_per_piece": 150},
    "Мандарин": {"query": "Tangerines, (mandarin oranges), raw", "unit": "pcs", "grams_per_piece": 80},
    "Лимон": {"query": "Lemons, raw, without peel", "unit": "pcs", "grams_per_piece": 100},
    "Лайм": {"query": "Limes, raw", "unit": "pcs", "grams_per_piece": 67},
    "Ківі": {"query": "Kiwifruit, green, raw", "unit": "pcs", "grams_per_piece": 75},
    "Персик": {"query": "Peaches, yellow, raw", "unit": "pcs", "grams_per_piece": 150},
    "Слива": {"query": "Plums, raw", "unit": "g"},
    "Виноград": {"query": "Grapes, red or green (European type, such as Thompson seedless), raw", "unit": "g"},
    "Ананас": {"query": "Pineapple, raw, all varieties", "unit": "g"},
    "Кавун": {"query": "Watermelon, raw", "unit": "g"},
    "Полуниця": {"query": "Strawberries, raw", "unit": "g"},
    "Малина": {"query": "Raspberries, raw", "unit": "g"},
    "Чорниця": {"query": "Blueberries, raw", "unit": "g"},
    "Вишня": {"query": "Cherries, sour, red, raw", "unit": "g"},
    "Ізюм": {"query": "Raisins, seedless", "unit": "g"},
    "Курага": {"query": "Apricots, dried, sulfured, uncooked", "unit": "g"},
    "Чорнослив": {"query": "Plums, dried (prunes), uncooked", "unit": "g"},
    "Фініки": {"query": "Dates, medjool", "unit": "g"},
    "Кокосова стружка": {"query": "Nuts, coconut meat, dried (desiccated), not sweetened", "unit": "g"},

    "Волоський горіх": {"query": "Nuts, walnuts, english", "unit": "g"},
    "Мигдаль": {"query": "Nuts, almonds", "unit": "g"},
    "Фундук": {"query": "Nuts, hazelnuts or filberts", "unit": "g"},
    "Кешью": {"query": "Nuts, cashew nuts, raw", "unit": "g"},
    "Арахіс": {"query": "Peanuts, all types, raw", "unit": "g"},
    "Арахісова паста": {"query": "Peanut butter, smooth style, without salt", "unit": "g"},
    "Насіння соняшнику": {"query": "Seeds, sunflower seed kernels, dried", "unit": "g"},
    "Насіння гарбуза": {"query": "Seeds, pumpkin and squash seed kernels, dried", "unit": "g"},
    "Кунжут": {"query": "Seeds, sesame seeds, whole, dried", "unit": "g"},
    "Насіння чіа": {"query": "Seeds, chia seeds, dried", "unit": "g"},

    "Олія соняшникова": {"query": "Oil, sunflower, linoleic, (approx. 65%)", "unit": "ml", "fdc_id": 171025},
    "Олія оливкова": {"query": "Oil, olive, salad or cooking", "unit": "ml"},
    "Олія кокосова": {"query": "Oil, coconut", "unit": "ml"},

    "Цукор": {"query": "Sugars, granulated", "unit": "g"},
    "Цукор коричневий": {"query": "Sugars, brown", "unit": "g"},
    "Цукрова пудра": {"query": "Sugars, powdered", "unit": "g"},
    "Мед": {"query": "Honey", "unit": "g"},
    "Кленовий сироп": {"query": "Syrups, maple", "unit": "ml"},
    "Варення": {"query": "Jams and preserves", "unit": "g"},
    "Какао-порошок": {"query": "Cocoa, dry powder, unsweetened", "unit": "g"},
    "Шоколад чорний": {"query": "Chocolate, dark, 70-85% cacao solids", "unit": "g"},
    "Шоколад молочний": {"query": "Candies, milk chocolate", "unit": "g"},
    "Ванільний екстракт": {"query": "Vanilla extract", "unit": "ml"},
    "Розпушувач": {"query": "Leavening agents, baking powder, double-acting, sodium aluminum sulfate", "unit": "g"},
    "Сода харчова": {"query": "Leavening agents, baking soda", "unit": "g"},
    "Дріжджі сухі": {"query": "Leavening agents, yeast, baker's, active dry", "unit": "g"},
    "Желатин": {"query": "Gelatins, dry powder, unsweetened", "unit": "g"},

    "Майонез": {"query": "Salad dressing, mayonnaise, regular", "unit": "g"},
    "Кетчуп": {"query": "Catsup", "unit": "g"},
    "Гірчиця": {"query": "Mustard, prepared, yellow", "unit": "g"},
    "Хрін": {"query": "Horseradish, prepared", "unit": "g"},
    "Соєвий соус": {"query": "Soy sauce made from soy and wheat (shoyu)", "unit": "ml"},
    "Вустерський соус": {"query": "Sauce, worcestershire", "unit": "ml"},
    "Оцет столовий": {"query": "Vinegar, distilled", "unit": "ml"},
    "Оцет яблучний": {"query": "Vinegar, cider", "unit": "ml"},
    "Кокосове молоко": {"query": "Nuts, coconut milk, canned (liquid expressed from grated meat and water)", "unit": "ml"},
    "Бульйон курячий": {"query": "Soup, chicken broth, ready-to-serve", "unit": "ml"},

    "Сіль": {"query": "Salt, table", "unit": "g"},
    "Перець чорний мелений": {"query": "Spices, pepper, black", "unit": "g"},
    "Паприка": {"query": "Spices, paprika", "unit": "g"},
    "Перець чилі мелений": {"query": "Spices, chili powder", "unit": "g"},
    "Кориця": {"query": "Spices, cinnamon, ground", "unit": "g"},
    "Лавровий лист": {"query": "Spices, bay leaf", "unit": "g"},
    "Куркума": {"query": "Spices, turmeric, ground", "unit": "g"},
    "Кмин": {"query": "Spices, cumin seed", "unit": "g"},
    "Орегано": {"query": "Spices, oregano, dried", "unit": "g"},
    "Базилік сушений": {"query": "Spices, basil, dried", "unit": "g"},
    "Чебрець": {"query": "Spices, thyme, dried", "unit": "g"},
    "Мускатний горіх": {"query": "Spices, nutmeg, ground", "unit": "g"},
    "Часник сушений": {"query": "Spices, garlic powder", "unit": "g"},
    "Імбир мелений": {"query": "Spices, ginger, ground", "unit": "g"},
    "Карі": {"query": "Spices, curry powder", "unit": "g"},

    "Кріп": {"query": "Dill weed, fresh", "unit": "g"},
    "Петрушка": {"query": "Parsley, fresh", "unit": "g"},
    "Кінза": {"query": "Coriander (cilantro) leaves, raw", "unit": "g"},
    "Базилік": {"query": "Basil, fresh", "unit": "g"},
    "М'ята": {"query": "Spearmint, fresh", "unit": "g"},

    "Вода": {"query": "Water, tap, drinking", "unit": "ml"},
    "Апельсиновий сік": {"query": "Orange juice, raw", "unit": "ml"},
    "Вино біле сухе": {"query": "Alcoholic beverage, wine, table, white", "unit": "ml"},
    "Вино червоне сухе": {"query": "Alcoholic beverage, wine, table, red", "unit": "ml"},
}