# Generated by Django 5.2.17 on 2026-10-06 07:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fridge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='назва')),
                ('instructions', models.TextField(help_text='Кожен крок з нового рядка.', verbose_name='приготування')),
                ('image', models.ImageField(blank=True, upload_to='recipes/', verbose_name='фото')),
                ('servings', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='порцій')),
                ('source_url', models.URLField(blank=True, verbose_name='джерело')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked_at', models.DateTimeField(auto_now_add=True, verbose_name='приготовано')),
                ('calories_consumed', models.FloatField(verbose_name='калорії')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_logs', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'запис журналу',
                'verbose_name_plural': 'журнал',
                'ordering': ['-cooked_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='кількість')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fridge.product', verbose_name='продукт')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='рецепт')),
            ],
            options={
                'verbose_name': 'інгредієнт',
                'verbose_name_plural': 'інгредієнти',
                'constraints': [models.UniqueConstraint(fields=('recipe', 'product'), name='unique_recipe_product')],
            },
        ),
    ]
