# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='фото з джерела'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='власник'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='optional',
            field=models.BooleanField(default=False, verbose_name='за смаком'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='джерело'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='кількість'),
        ),
        migrations.CreateModel(
            name='RecipeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='посилання')),
                ('status', models.CharField(choices=[('draft', 'чернетка'), ('saved', 'збережено'), ('failed', 'помилка')], default='draft', max_length=10, verbose_name='статус')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='результат розбору')),
                ('error', models.TextField(blank=True, verbose_name='помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe', verbose_name='рецепт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_imports', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'імпорт рецепта',
                'verbose_name_plural': 'імпорти рецептів',
                'ordering': ['-created_at'],
            },
        ),
    ]
